# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy-dev:
  
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
  
  deploy-homol:
  
    runs-on: ubuntu-latest
    environment:
      name: hml
    needs: deploy-dev
    steps:
    - name: Send email to testers
      uses: dawidd6/action-send-mail@v1.3.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_ADDRESS }}
        # going with mail app password
        password: ${{ secrets.GMAIL_PASS }}
        subject: New version available
        body: The api just got updated for testing, please give us your feedback after testing so it may go to production
        to: ${{ secrets.GMAIL_ADDRESS }}
        from: ${{ secrets.GMAIL_ADDRESS }}
  
  deploy-prod:
  
    runs-on: ubuntu-latest
    environment:
      name: livros-boot
    needs: deploy-homol
    steps:
    - name: Run a one-line script
      run: echo Deploy Heroku
